CREATE VIEW [dbo].[v_Customer]
	AS
	SELECT 
	   [cr].[CustomerId]
	  ,isnull([cr].[FirstName],'') +' '+ isnull([cr].[LastName],'') as [FullName]
      ,[cr].[Company]
      ,[cr].[Address]
      ,[cr].[City]
      ,[cr].[State]
      ,[cr].[Country]
      ,[cr].[PostalCode]
      ,[cr].[Phone]
      ,[cr].[Fax]
      ,[cr].[Email]
      ,isnull([em].[FirstName],'') + ' ' +isnull([em].[LastName],'') as [Support_FullName]
      ,[em].[FirstName]		as [Support_FirstName]
      ,[em].[Title]			as [Support_Title]
      ,[em].[ReportsTo]		as [Support_ReportsTo]
      ,[em].[BirthDate]		as [Support_BirthDate]
      ,[em].[HireDate]		as [Support_HireDate]
      ,[em].[Address]		as [Support_Address]
      ,[em].[City]			as [Support_City]
      ,[em].[State]			as [Support_State]
      ,[em].[Country]		as [Support_Country]
      ,[em].[PostalCode]	as [Support_PostalCode]
      ,[em].[Phone]			as [Support_Phone]
      ,[em].[Fax]			as [Support_Fax]
      ,[em].[Email]			as [Support_Email]
	FROM 
	[dbo].[Customer]	AS cr
	LEFT JOIN	[dbo].[Employee] AS em ON [cr].[SupportRepId] = [em].[EmployeeId]